title: Runbo Su
logo: /images/rs_cv.jpg
description: [<img src="/images/orcid.png" width="150" height="50">](https://orcid.org/0000-0001-5116-8207)
[<img src="/images/linkedin1.png" width="50" height="50">](https://www.linkedin.com/in/runbo-su-ab32a3151/)
show_downloads: false
theme: jekyll-theme-minimal
