title: Runbo Su
logo: /images/rs_cv.jpg
#description:
orcid: https://orcid.org/0000-0001-5116-8207
LinkedIn: https://www.linkedin.com/feed/?trk=sem-ga_campid.21228777300_asid.161774284317_crid.698137525090_kw.linkedin_d.c_tid.kwd-148086543_n.g_mt.e_geo.9108845
show_downloads: false
theme: jekyll-theme-minimal
